"""Regression cases generated by the new Base microcycle templates."""
from dataclasses import replace
from datetime import date
import re
from types import SimpleNamespace

import pytest

from performancelab.coaching.session_purpose import SessionPurpose
from performancelab.coaching.strategy import StrategyPlan
from performancelab.coaching.workout_generator import WorkoutGenerator
from performancelab.coaching.workout_templates import (
    CONTINUOUS_TEMPO_TEMPLATE, THRESHOLD_CRUISE_TEMPLATE,
    AEROBIC_HILLS_TEMPLATE, EASY_STRIDES_TEMPLATE,
)
from performancelab.training.planning import TrainingPlanAdapter, WorkoutOutcomeStatus
from tests.test_training_plan_adapter import make_plan, make_outcome, make_training_state

TEMPLATES = (CONTINUOUS_TEMPO_TEMPLATE, THRESHOLD_CRUISE_TEMPLATE,
             AEROBIC_HILLS_TEMPLATE, EASY_STRIDES_TEMPLATE)


def generated_workout(template):
    return WorkoutGenerator()._build_workout(
        slot=SimpleNamespace(purpose=SessionPurpose.INTENSITY, duration_minutes=45),
        scheduled_day=date(2026, 8, 7),
        template=template.for_sport("Trail Running"),
        coach_context=SimpleNamespace(),
        strategy_plan=StrategyPlan(
            strategy="BuildStrategy", phase="Base", volume_factor=1.0,
            target_sessions=5, intensity_sessions=1, long_sessions=1,
            recovery_days=2, key_session_focus="tempo",
        ),
    )


def executable_seconds(steps):
    """Count prescribed work and the maximum recovery between repetitions."""
    total = 0
    repetitions = 1
    for step in steps:
        interval = re.search(r"(\d+)×(?:(\d+) min(?: (\d+) sec)?|(\d+) sec)", step)
        if interval:
            repetitions = int(interval[1])
            total += repetitions * (int(interval[2] or 0)*60 + int(interval[3] or interval[4] or 0))
        elif step.startswith("Recover"):
            seconds = [int(n) for n in re.findall(r"\d+", step)]
            total += (repetitions - 1) * max(seconds)
        elif step.startswith(("Run ", "Warm up ", "Cool down ")):
            minutes = re.search(r"(\d+) min(?: (\d+) sec)?", step)
            if minutes:
                total += int(minutes[1])*60 + int(minutes[2] or 0)
    return total


@pytest.mark.parametrize("template", TEMPLATES)
def test_overload_adaptation_retains_base_stimulus_and_fits_duration(template):
    plan = make_plan()
    original = generated_workout(template)
    plan.workouts[1] = original
    outcome = make_outcome(plan=plan, status=WorkoutOutcomeStatus.MODIFIED,
                           planned_load=180, completed_load=360)
    adapted = TrainingPlanAdapter().adapt(
        plan=plan, outcomes=(outcome,), training_state=make_training_state(tsb=-25),
        reference_day=date(2026, 8, 5),
    ).workouts[1]
    assert adapted.duration < original.duration
    assert executable_seconds(adapted.structure) <= adapted.duration.total_seconds()
    assert adapted.structure[-1] == original.structure[-1]
    text = " ".join(adapted.structure)
    if template is CONTINUOUS_TEMPO_TEMPLATE:
        assert "continuous at controlled tempo (RPE 6–7/10)" in text
        assert "×" not in text
    elif template is THRESHOLD_CRUISE_TEMPLATE:
        assert "4×4 min 45 sec near LT2 at RPE 7/10" in text
        assert "Recover 60–90 sec easy between repetitions" in adapted.structure
        assert "Recover 2 min" not in text
    elif template is AEROBIC_HILLS_TEMPLATE:
        assert "5×4 min uphill at controlled aerobic effort (RPE 6–7/10); do not sprint" in text
        assert "Recover 90 sec easy downhill between repetitions" in adapted.structure
    else:
        assert "Complete 6×20 sec relaxed strides; do not sprint" in adapted.structure
        assert "Recover fully with 70–100 sec easy between strides" in adapted.structure
        assert "fast" not in text
    assert plan.workouts[1] == original


def test_easy_increase_adds_easy_time_without_converting_strides_to_speed():
    original = generated_workout(EASY_STRIDES_TEMPLATE)
    adapted = TrainingPlanAdapter._increase_future_easy_workouts(
        workouts=[original], reference_day=date(2026, 8, 5),
        adaptation_deadline=None, missing_load=None,
    )[0]
    assert adapted.duration == original.duration * 1.05
    assert "Complete 6×20 sec relaxed strides; do not sprint" in adapted.structure
    assert original.structure[2] == adapted.structure[2]
    assert executable_seconds(adapted.structure) <= adapted.duration.total_seconds()
    assert "fast" not in " ".join(adapted.structure)


@pytest.mark.parametrize("template", TEMPLATES)
def test_successive_adaptations_never_fall_back_to_another_stimulus(template):
    workout = generated_workout(template)
    for _ in range(3):
        duration = workout.duration * .8
        structure = TrainingPlanAdapter._adapted_base_template_structure(
            workout=workout, duration=duration,
        )
        assert structure is not None
        assert executable_seconds(structure) <= duration.total_seconds()
        assert structure[-1] == workout.structure[-1]
        workout = replace(workout, duration=duration, structure=structure)


@pytest.mark.parametrize("template", TEMPLATES)
def test_custom_structure_in_new_templates_is_not_overwritten(template):
    workout = generated_workout(template)
    edited = replace(workout, structure=(*workout.structure, "User instruction: stop after the third climb"))
    assert TrainingPlanAdapter._reduce_future_demanding_workouts(
        workouts=[edited], reference_day=date(2026, 8, 5),
        adaptation_deadline=None, reduction_fraction=.2,
    ) == [edited]
    assert TrainingPlanAdapter._increase_future_easy_workouts(
        workouts=[edited], reference_day=date(2026, 8, 5),
        adaptation_deadline=None, missing_load=None,
    ) == [edited]


@pytest.mark.parametrize("phase", ["Taper", "Race", "Recovery", "Regeneration"])
def test_new_templates_keep_protected_phase_guards(phase):
    workout = replace(generated_workout(CONTINUOUS_TEMPO_TEMPLATE), phase=phase)
    assert TrainingPlanAdapter._reduce_future_demanding_workouts(
        workouts=[workout], reference_day=date(2026, 8, 5),
        adaptation_deadline=None, reduction_fraction=.2,
    ) == [workout]


def test_new_templates_keep_past_and_next_race_guards():
    workout = generated_workout(AEROBIC_HILLS_TEMPLATE)
    for reference, deadline in [(workout.day, None), (date(2026,8,5), workout.day)]:
        assert TrainingPlanAdapter._reduce_future_demanding_workouts(
            workouts=[workout], reference_day=reference,
            adaptation_deadline=deadline, reduction_fraction=.2,
        ) == [workout]
