"""
PerformanceLab

Streamlit application.
"""

from datetime import date, datetime, time, timedelta
from pathlib import Path

import streamlit as st

from components import (
    show_athlete_panel,
    show_dashboard,
    show_selected_workout_route,
    show_sidebar,
    show_workout_editor,
)

from performancelab import (
    Athlete,
    create_workout,
)

from performancelab.storage.json_repository import (
    JsonAthleteRepository,
)

from performancelab.coaching import Coach
from performancelab.training.config import AthleteAvailability


# ======================================================
# Page configuration
# ======================================================

st.set_page_config(
    page_title="PerformanceLab",
    page_icon="📈",
    layout="wide",
)

APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent
DATA_DIR = PROJECT_ROOT / "data" / "athletes"

repository = JsonAthleteRepository(
    DATA_DIR / "athlete.json"
)

# ======================================================
# Demonstration athlete
# ======================================================

def create_demo_athlete() -> Athlete:

    athlete = Athlete(
        name="Pedro",
        weight=70,
        ftp=280,
        max_hr=190,
        resting_hr=50,
    )

    athlete.availability = AthleteAvailability.from_minutes(
        monday=60,
        wednesday=60,
        saturday=120,
    )

    demo_workouts = [
        create_workout(
            sport="Running",
            workout_date=date.today() - timedelta(days=13),
            distance=8,
            duration=timedelta(minutes=45),
            elevation_gain=120,
            rpe=5,
            title="Easy Run",
        ),
        create_workout(
            sport="Cycling",
            workout_date=date.today() - timedelta(days=11),
            distance=42,
            duration=timedelta(hours=1, minutes=30),
            elevation_gain=450,
            rpe=6,
            title="Endurance Ride",
        ),
        create_workout(
            sport="Running",
            workout_date=date.today() - timedelta(days=9),
            distance=12,
            duration=timedelta(hours=1, minutes=5),
            elevation_gain=210,
            rpe=7,
            title="Tempo Run",
        ),
        create_workout(
            sport="Swimming",
            workout_date=date.today() - timedelta(days=7),
            distance=2.5,
            duration=timedelta(minutes=50),
            elevation_gain=0,
            rpe=5,
            title="Pool Session",
        ),
        create_workout(
            sport="Cycling",
            workout_date=date.today() - timedelta(days=5),
            distance=55,
            duration=timedelta(hours=2),
            elevation_gain=700,
            rpe=7,
            title="Long Ride",
        ),
        create_workout(
            sport="Running",
            workout_date=date.today() - timedelta(days=3),
            distance=10,
            duration=timedelta(minutes=52),
            elevation_gain=160,
            rpe=6,
            title="Steady Run",
        ),
        create_workout(
            sport="Running",
            workout_date=date.today(),
            distance=16,
            duration=timedelta(hours=1, minutes=25),
            elevation_gain=320,
            rpe=8,
            title="Long Run",
        ),
    ]

    for workout in demo_workouts:
        athlete.history.add(workout)

    today = date.today()
    monday = today - timedelta(days=today.weekday())

    athlete.training_plan.schedule(
    scheduled_at=datetime.combine(
            monday,
            time(hour=18),
        ),
        sport="Running",
        title="Easy Run",
        duration=timedelta(minutes=45),
        description="Easy aerobic run",
    )

    athlete.training_plan.schedule(
        scheduled_at=datetime.combine(
            monday + timedelta(days=2),
            time(hour=18),
        ),
        sport="Running",
        title="Intervals",
        duration=timedelta(minutes=60),
        description="6 × 800 m",
    )

    athlete.training_plan.schedule(
        scheduled_at=datetime.combine(
            monday + timedelta(days=5),
            time(hour=8),
        ),
        sport="Running",
        title="Long Run",
        duration=timedelta(minutes=90),
        description="Long endurance run",
    )

    return athlete


# ======================================================
# Session state
# ======================================================

def generate_weekly_plan(
    athlete: Athlete,
) -> None:
    """
    Replace the athlete's current planned workouts with a plan
    generated by the coaching engine.
    """

    weekly_plan = Coach().plan(
        athlete=athlete,
    )

    athlete.training_plan.clear()

    for workout in weekly_plan.workouts:
        athlete.training_plan.add(
            workout
        )

def regenerate_weekly_plan() -> None:
    """
    Generates a new weekly plan for the current athlete.
    """

    athlete = st.session_state.athlete

    generate_weekly_plan(
        athlete,
    )

    st.session_state.notice = (
        "Plano semanal gerado."
    )

def initialize_session_state() -> None:

    if "athlete" not in st.session_state:

        if repository.exists():

            try:

                st.session_state.athlete = repository.load()

            except Exception as error:

                st.error(
                    "Could not load the saved athlete."
                )

                st.exception(error)

                st.session_state.athlete = (
                    create_demo_athlete()
                )

        else:

            st.session_state.athlete = (
                create_demo_athlete()
            )

            repository.save(
                st.session_state.athlete,
            )

    if "notice" not in st.session_state:
        st.session_state.notice = None

    if "plan_error" not in st.session_state:
        st.session_state.plan_error = None

    if "confirm_delete" not in st.session_state:
        st.session_state.confirm_delete = False

    if "edit_workout" not in st.session_state:
        st.session_state.edit_workout = False

    if "page" not in st.session_state:
        st.session_state.page = "dashboard"

# ======================================================
# Application
# ======================================================

initialize_session_state()

athlete: Athlete = st.session_state.athlete

athlete = show_sidebar(
    athlete,
    on_generate_plan=regenerate_weekly_plan,
)

page = st.session_state.page

if st.session_state.plan_error:

    st.error(
        "Não foi possível gerar o plano semanal."
    )

    st.code(
        st.session_state.plan_error
    )

    st.session_state.plan_error = None

if (
    page == "dashboard"
    and st.session_state.notice
):
    st.success(
        st.session_state.notice
    )
    st.session_state.notice = None

if page == "dashboard":

    selected_workout = show_dashboard(
        athlete,
    )

    show_workout_editor(
        athlete,
        selected_workout,
    )

    show_selected_workout_route(
        selected_workout,
    )

elif page == "athlete":

    athlete = show_athlete_panel(
        athlete,
    )

else:

    TITLES = {
        "training": "Treinos",
        "goals": "Objetivos",
        "events": "Eventos",
        "analytics": "Análises",
        "statistics": "Estatísticas",
        "equipment": "Equipamento",
        "settings": "Configurações",
    }

    st.title(
        TITLES.get(page, page.title())
    )

    st.info(
        "🚧 Página em desenvolvimento."
    )

st.session_state.athlete = athlete

repository.save(
    athlete,
)

if (
    page == "athlete"
    and st.session_state.page == "dashboard"
):
    st.rerun()